<h1>Scala map problems</h1>
<b>Note:</b> Please enter your problem solutions in the three cells immediately below this one. All other work should go below these two cells (and will be ignored by the graders!)

In [2]:
//PROBLEM 1 SOLUTION
val test_data = "widgets 103.24,eggs 345.22,milk 231.25,widgets 123.11,milk 14.2" 

//YOUR FUNCTION SHOULD GO HERE
def inventory_value(text: String) = 
  text.split(",").map(i => i.split(" ")).map(i => (i(0),i(1).toDouble)).groupBy(_._1).mapValues(x => x.map(i => i._2).sum)


//Test your function here
inventory_value(test_data)

test_data: String = widgets 103.24,eggs 345.22,milk 231.25,widgets 123.11,milk 14.2
inventory_value: (text: String)scala.collection.immutable.Map[String,Double]
res1: scala.collection.immutable.Map[String,Double] = Map(widgets -> 226.35, eggs -> 345.22, milk -> 245.45)


In [3]:
//PROBLEM 2 SOLUTION
val test_data = "able was i ere i saw elba, and that was before i was able and could see elba!"

//YOUR FUNCTION SHOULD GO HERE
def letter_count(text:String) = 
  text.toCharArray().filter(_.isLetter).map(i => (i,1)).groupBy(_._1).mapValues(x => x.map(i => i._2).sum)


//Test your function here
letter_count(test_data)

test_data: String = able was i ere i saw elba, and that was before i was able and could see elba!
letter_count: (text: String)scala.collection.immutable.Map[Char,Int]
res2: scala.collection.immutable.Map[Char,Int] = Map(e -> 10, s -> 5, n -> 2, t -> 2, u -> 1, f -> 1, a -> 11, i -> 3, b -> 5, l -> 5, c -> 1, h -> 1, r -> 2, w -> 4, o -> 2, d -> 3)


In [18]:
//PROBLEM 3 SOLUTION
val sample_essay = """able was i ere i saw elba
a man a plan a canal panama
the future is uncertain and the end is always near"""

//Your function should go here
def essay_grade(essay:String) = {

  ((1-essay.split("\n").map(i => i.toCharArray.map(i => if ((i=='a')|(i=='e')|(i=='i')|(i=='o')|(i=='u')) 1 else 0)
                            .reduce(_+_).toDouble/i.length).reduce(_+_)/essay.split("\n").length)*100).toInt
}

//Test your function here
essay_grade(sample_essay)

sample_essay: String =
able was i ere i saw elba
a man a plan a canal panama
the future is uncertain and the end is always near
essay_grade: (essay: String)Int
res16: Int = 62


<h1>Problem 1</h1>

Write a scala function "inventory_value" that takes a single argument, inventory, as an input and reports the total value of each item in the list. 

For example, if the inventory list is in the form:
"widgets 103.24,eggs 345.22,milk 231.25,widgets 123.11,milk 14.2” your function should output:

res58: scala.collection.immutable.Map[String,Double] = Map(eggs -> 345.22, milk -> 245.45, widgets -> 226.35)


You can assume that the string is well formed. I.e., there are no spaces other than the ones between the product name and the inventory value, that each item pair is separated by a comma, each item name is exactly one word, and each value is convertible into double without errors.

Helpful functions:

1. mapValues: m mapValues f applies f to the values of key,value pairs in m (you can
get this using a group by operation) 

2. sum: adds up numbers in a collection
Though you can use reduce for this, using mapValues and sum may be simpler

In [1]:
val test_data = "widgets 103.24,eggs 345.22,milk 231.25,widgets 123.11,milk 14.2" 

Intitializing Scala interpreter ...

Spark Web UI available at http://localhost:4042
SparkContext available as 'sc' (version = 3.2.0, master = local[*], app id = local-1646627870150)
SparkSession available as 'spark'


test_data: String = widgets 103.24,eggs 345.22,milk 231.25,widgets 123.11,milk 14.2


In [2]:
val a = test_data.split(",").map(i => i.split(" ")).map(i => (i(0),i(1).toDouble))
a.groupBy(_._1)//.mapValues(x => x.map(i => i._2).sum)

a: Array[(String, Double)] = Array((widgets,103.24), (eggs,345.22), (milk,231.25), (widgets,123.11), (milk,14.2))
res0: scala.collection.immutable.Map[String,Array[(String, Double)]] = Map(widgets -> Array((widgets,103.24), (widgets,123.11)), eggs -> Array((eggs,345.22)), milk -> Array((milk,231.25), (milk,14.2)))


In [6]:
val x = Array(('a',3),('b',2))
x.map(i => i._2).sum

x: Array[(Char, Int)] = Array((a,3), (b,2))
res4: Int = 5


In [7]:

inventory_value(test_data) //should return
//res1: scala.collection.immutable.Map[String,Double] = Map(eggs -> 345.22, milk -> 245.45, widgets -> 226.35)

res5: scala.collection.immutable.Map[String,Double] = Map(widgets -> 226.35, eggs -> 345.22, milk -> 245.45)


<h2>mapValues function</h2>

In [8]:
val d = Map('a' -> 12,'b'->15) // Creates a key --> value map
d.mapValues(i => i*i) //Applies the function to the values of d 

d: scala.collection.immutable.Map[Char,Int] = Map(a -> 12, b -> 15)
res6: scala.collection.immutable.Map[Char,Int] = Map(a -> 144, b -> 225)


<h1>problem 2</h1>
Write a scala function that returns the count of each letter in a text string. 

For example, if the input string is "able was i ere i saw elba, and that was before i was able and could see elba!”, your program should return:

Map(e -> 10, s -> 5, n -> 2, t -> 2, u -> 1, f -> 1, a -> 11, i -> 3, b -> 5, l -> 5, c -> 1, h -> 1, r -> 2, w -> 4, o -> 2, d -> 3)

Note that you should only count the letters and ignore all punctuation, numbers, spaces, or any special characters. 

The scala function isLetter returns true if a character is a letter and false otherwise.

In [9]:
val text = "able was i ere i saw elba, and that was before i was able and could see elba!"
def letter_count(text:String) = 
  text.toCharArray().filter(_.isLetter).map(i => (i,1)).groupBy(_._1).mapValues(x => x.map(i => i._2).sum)

letter_count(text)
//Should return:
//scala.collection.immutable.Map[Char,Int] = Map(e -> 10, s -> 5, n -> 2, t -> 2, u -> 1, f -> 1, a -> 11, i -> 3, b -> 5, l -> 5, c -> 1, h -> 1, r -> 2, w -> 4, o -> 2, d -> 3)


text: String = able was i ere i saw elba, and that was before i was able and could see elba!
letter_count: (text: String)scala.collection.immutable.Map[Char,Int]
res7: scala.collection.immutable.Map[Char,Int] = Map(e -> 10, s -> 5, n -> 2, t -> 2, u -> 1, f -> 1, a -> 11, i -> 3, b -> 5, l -> 5, c -> 1, h -> 1, r -> 2, w -> 4, o -> 2, d -> 3)


In [10]:
val text = "able was i ere i saw elba, and that was before i was able and could see elba!"
text.toCharArray().filter(_.isLetter).map(i => (i,1)).groupBy(_._1).mapValues(x => x.map(i => i._2).sum)

text: String = able was i ere i saw elba, and that was before i was able and could see elba!
res8: scala.collection.immutable.Map[Char,Int] = Map(e -> 10, s -> 5, n -> 2, t -> 2, u -> 1, f -> 1, a -> 11, i -> 3, b -> 5, l -> 5, c -> 1, h -> 1, r -> 2, w -> 4, o -> 2, d -> 3)


<h2>isLetter</h2>
<li>returns true if a character is a letter of the alphabet and false otherwise

In [11]:
'p'.isLetter

res9: Boolean = true


In [12]:
'2'.isLetter

res10: Boolean = false


In [13]:
'?'.isLetter

res11: Boolean = false


In [14]:
' '.isLetter

res12: Boolean = false


<h1>Problem 3</h1>
An English teacher hates sentences with excessive vowels and wants you to write a program that can grade millions of SAT essays by calculating the average number of vowels per sentence in the essay. For example, if the essay contains the following text:

able was I ere I saw elba<br>
a man a plan a canal panama<br>
the future is uncertain and the end is always near<br>

then the essay gets a vowel score of 0.3701234567901235 since the vowel to character ratio in each sentence is: 0.4, 0.37037037037037035, 0.34. In this English teacher's world, characters include anything that is not a vowel (spaces, punctuation, etc.).

Write a function <span style="color:blue">essay_grade</span> that, for a given essay provided as an argument, calculates the vowel ratio and returns (1-the ratio) times 100 as the grade on the exam. The final grade should be returned as a truncated Int (62 for the example case). For the purposes of this problem, you must use both the map function as well as the reduce function and you can assume the text is in lower case (i.e., it should work for the example above)

In [15]:
val sample_essay = """able was i ere i saw elba
a man a plan a canal panama
the future is uncertain and the end is always near"""

//Your function should go here
def essay_grade


//Test your function here
essay_grade(sample_essay)

<console>: 36: error: Unit does not take parameters

In [ ]:
val sample_essay = """able was i ere i saw elba
a man a plan a canal panama
the future is uncertain and the end is always near"""

//essay_grade(sample_essay) //Should return 62

val sentences = sample_essay.split("\n")
val rates = sentences.map(i => i.toCharArray.map(i => if ((i=='a')|(i=='e')|(i=='i')|(i=='o')|(i=='u')) 1 else 0).reduce(_+_).toDouble/i.length)
((1-rates.reduce(_+_)/rates.length)*100).toInt

In [ ]:
"able was i ere i saw elba".toCharArray.map(i => if ((i=='a')|(i=='e')|(i=='i')|(i=='o')|(i=='u')) 1 else 0).reduce(_+_).toDouble

In [ ]:
"able was i ere i saw elba".length